<?php
require "../partials/_dbconnect.php";

// if payment is done perform these operations 
if(isset($_POST['paid']))
{  
    $u_item_id= array();
    foreach($_POST['item_ids'] as $item_ids)
    {
        array_push($u_item_id, $item_ids);
    }
    $u_item_quantity= array();
    foreach($_POST['item_quantities'] as $item_quantities)
    {
        array_push($u_item_quantity, $item_quantities);
    }
    $user_id=$_POST['u_user'];
    $grand_total=$_POST['grand_total'];
    // generate an unique invoice number 
    $sql_invoice="INSERT INTO `invoice`( `user_id`, `amount`) VALUES ('$user_id','$grand_total')";
    $result=mysqli_query($conn, $sql_invoice);
    // find the latest invoice generated by logged in user 
    $sql_get_inv_id="SELECT * FROM `invoice` WHERE `user_id`='$user_id' ORDER by `invoice_date` DESC";
    $result=mysqli_query($conn,$sql_get_inv_id);
    $inv_row=mysqli_fetch_assoc($result);
    // store the invoice id 
    $invoice_id=$inv_row['invoice_id'];
    $index=0;
    $len=count($u_item_id);
    // for each cart items perform these operations 
    while($index<$len)
    {
        $d_item_id=$u_item_id[$index];
        $d_item_quantity=$u_item_quantity[$index];
        // get all the information about that perticular item 
        $sql="SELECT  * FROM `item` WHERE `item_id`=$d_item_id";
        
        $result=mysqli_query($conn,$sql);
        $row=mysqli_fetch_assoc($result);
        // store required deta 
        $stock=$row['stock'];
        $o_price=$row['price'];
        $o_name=$row['item_name'];
        $stock=$stock-$d_item_quantity;
        // update the stock value in the item details 
        $sqlupdate="UPDATE `item` SET `stock`='$stock' WHERE `item_id`=$d_item_id";
        $result=mysqli_query($conn,$sqlupdate);

        // set sql query for new order 
        $sql_order="INSERT INTO `orders`( `invoice_id`, `user_id`, `item_id`, `quantity`, `price`, `item_name`) VALUES ('$invoice_id','$user_id','$d_item_id','$d_item_quantity','$o_price','$o_name')";
        // generate a new order with unique order id 
        $result=mysqli_query($conn,$sql_order);

        $index++;

    }

    // get the user id who's cart is to be updated 
    $u_user=$_POST['u_user'];
    // empty the cart after the payment is successful 
    $sql_update_cart="DELETE FROM `cart` WHERE `user_id`=$u_user";
    if($result=mysqli_query($conn,$sql_update_cart))
    {
        $alert="Your order has been placed successfully";
        header("location: /store/pages/cart.php?alert=$alert");
        

    }
    else{
        $error="something went wrong your cart did not updated";
        header("location: /store/pages/cart.php?error=$error");

    }
}


?>
