<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>cart</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <!-- css links  -->
    <link rel="stylesheet" href="/store/css/util.css">
    <link rel="stylesheet" href="/store/css/style.css">

</head>

<body>
    <?php
// call header 
 require_once "../partials/_header.php";
 require_once "../partials/_order_modal.php";

 if(isset($_SESSION['loggedin']) && $_SESSION['loggedin']== true && $_SESSION['type']=='user')
{$user_id=$_SESSION['id'];
    $sql="SELECT * FROM `cart` WHERE `user_id`='$user_id'";
    $result= mysqli_query($conn,$sql);
    echo '<div class="container">
    <h1 style="text-align:center">Your cart</h1>
    <table width="100%">
        <thead>
            <tr>
            <th >Item</th>
            <th >Price</th>
            <th >Quantity</th>
            <th >Total Price</th>
            <th ></th>
            </tr>
        </thead>
        <tbody>';
        // print cart details one by one 
        while($row=mysqli_fetch_assoc($result)){
            $item_id=$row['item_id'];
            $sql="SELECT * FROM `item` WHERE `item_id`='$item_id'";
            $result2=mysqli_query($conn,$sql);
            $row2=mysqli_fetch_assoc($result2);
            $item_name=$row2['item_name'];
            $photo=$row2['photo'];
            $price=$row2['price'];
            $quantity=$row['number'];
            $totalPrice=$quantity*$price;
            echo '<tr>
            <td><div class="cartitem"><img src="/store/img/product/'.$photo.'" alt="'.$item_name.'"> <div class="center">'.$item_name.'</div></div></td>
            <td><div class="center"><p style="text-align:center">Rs'.$price.'</p></div></td>
            <td><div class="center"><form action="/store/handlers/cart_handler.php" method="post"><input type="number" style="width: 30px" name="ucart" id="" value="'.$quantity.'" min="1">
                                    <input type="hidden" name="cart_id" value="'.$row['id'].'">
                                    <input type="hidden" name="price" value="'.$row['price'].'">

                                    <input class="btn-2" type="submit" value="update">
                                    </form></div></td>
            <td><div class="center"><p style="text-align:center">Rs '.$totalPrice.'</p></div></td>
            <td><div class="center"><form action="/store/handlers/cart_handler.php" method="post">
                                    <input type="hidden" name="d_cart_id" value="'.$row['id'].'">
                                    <input class="btn-2" type="submit" value="Delete">
                                    </form></div></td></div></td>
        </tr>';

            



        }
        echo '</tbody>


        </table>

        <button class="btn-2 " onclick="document.getElementById(`order`).style.display=`block`">Place Order</button>
        
        ';
    


}

// // if payment is done perform these operations 
// if(isset($_POST['paid']))
// {  
//     // generate an unique invoice number 
//     $sql_invoice="INSERT INTO `invoice`( `user_id`, `amount`) VALUES ('$user_id','$grand_total')";
//     $result=mysqli_query($conn, $sql_invoice);
//     // find the latest invoice generated by logged in user 
//     $sql_get_inv_id="SELECT * FROM `invoice` WHERE `user_id`='$user_id' ORDER by `invoice_date` DESC";
//     $result=mysqli_query($conn,$sql_get_inv_id);
//     $inv_row=mysqli_fetch_assoc($result);
//     // store the invoice id 
//     $invoice_id=$inv_row['invoice_id'];
//     $index=0;
//     $len=count($d_item_id);
//     // for each cart items perform these operations 
//     while($index<$len)
//     {
//         $u_item_id=$d_item_id[$index];
//         $u_item_quantity=$d_item_quantity[$index];
//         // get all the information about that perticular item 
//         $sql="SELECT  * FROM `item` WHERE `item_id`=$u_item_id";
        
//         $result=mysqli_query($conn,$sql);
//         $row=mysqli_fetch_assoc($result);
//         // store required deta 
//         $stock=$row['stock'];
//         $o_price=$row['price'];
//         $o_name=$row['item_name'];
//         $stock=$stock-$u_item_quantity;
//         // update the stock value in the item details 
//         $sqlupdate="UPDATE `item` SET `stock`='$stock' WHERE `item_id`=$u_item_id";
//         $result=mysqli_query($conn,$sqlupdate);

//         // set sql query for new order 
//         $sql_order="INSERT INTO `orders`( `invoice_id`, `user_id`, `item_id`, `quantity`, `price`, `item_name`) VALUES ('$invoice_id','$user_id','$u_item_id','$u_item_quantity','$o_price','$o_name')";
//         // generate a new order with unique order id 
//         $result=mysqli_query($conn,$sql_order);

//         $index++;

//     }

//     // get the user id who's cart is to be updated 
//     $u_user=$_POST['u_user'];
//     // empty the cart after the payment is successful 
//     $sql_update_cart="DELETE FROM `cart` WHERE `user_id`=$u_user";
//     if($result=mysqli_query($conn,$sql_update_cart))
//     {
//         $alert="Your order has been placed successfully";
//         header("location: /store/pages/cart.php?alert=$alert");
        

//     }
//     else{
//         $error="something went wrong your cart did not updated";
//         header("location: /store/pages/cart.php?error=$error");

//     }
// }




        // call footer 
require_once "../partials/_footer.php";
?>



           


        
</div>




</body>

</html>